### ISSUE TITLE
Possible bug in _decode_elements

### ISSUE THREAD

**Issue by c00kiemon5ter** [peppelinux/pyMultiLDAP#1]
https://github.com/peppelinux/pyMultiLDAP/blob/dd8dcbba0a4567a51a119f696d9b1f5c7ca3219e/client.py#L45-L47

This seems wrong:

```python
e.decode(self.conf['encoding'] if isinstance(e, bytes) else e)
```

I am guessing what you wanted was:

```python
e.decode(self.conf['encoding']) if isinstance(e, bytes) else e
```

---

progression on this:

- use proper names
- accumulate results

```python
result = {
    attr_name: decoded_vals
    for attr_name, attr_vals in attr_dict.items()
    for decoded_vals in [[
        decoded_val
        for attr_val in attr_vals
        for decoded_val in [
            attr_val.decode(self.conf['encoding'])
            if isinstance(attr_val, bytes)
            else attr_val
        ]
    ]]
}
```

Nesting cannot be avoided; it follows the structure of the data. What you can do is split the different things you do in separate functions.

```python
def _decode_elements(self, attr_dict):
    def decode_attr_val(attr_val, encoding):
        value = (
            attr_val.decode(encoding)
            if isinstance(attr_val, bytes)
            else attr_val
        )
        return value

    def decode_attr_vals(attr_vals, encoding):
        values = [decode_attr_val(attr_val, encoding) for attr_val in attr_vals]
        return values

    encoding = self.conf['encoding']
    result = {
        attr_name: decode_attr_vals(attr_vals, encoding)
        for attr_name, attr_vals in attr_dict.items()
    }
    return result

```

**Comment by peppelinux** [comment]
@c00kiemon5ter great, nice to see you here.
I found a fix in your suggestion, but also a doubt about how the decoding methods Is still working! A mistery, I'll patch.

I put those code in a bunch of millisecondi Just to get things working, I confess that for a simple thing like this I wouldn't use nested function but... Tomorrow Is another day.

Really appreciate your contribute, I'll go further for a release candidate with the slapd-sock integration. That RC will consider this thread.

PS: a day Will talk about a I/O communication schema, json based, to integrate in satosa the opportunity to have standalone microservices. I love gevent and offtopics!

**Comment by peppelinux** [comment]
Done, thx
