### ISSUE TITLE
AttributeError: module 'gevent' has no attribute 'signal'

### ISSUE THREAD

**Issue by FandaOG** [peppelinux/pyMultiLDAP#2]
Hi,

I tried this package but I've got an error:
`multildapd.py -conf setting.py -port 1234`
```
[2021-07-14 06:35:31,182] [INFO] multildapd: Process run on pid: 322
Traceback (most recent call last):
  File "/usr/local/bin/multildapd.py", line 259, in <module>
    gevent.signal(signal.SIGTERM, stop_app, **{'pidfile': pidfile,
AttributeError: module 'gevent' has no attribute 'signal'
```

Steps to reproduce:
1. I use docker (I tried local mashine too but same result - Ubuntu Python 3.8) `docker run -it python:3.6 /bin/bash`
2. `pip3 install proxyldap`
3. create setting.py from example
4. `multildapd.py -conf setting.py -port 1234`
this return error:
```
[2021-07-14 06:35:31,182] [INFO] multildapd: Process run on pid: 322
Traceback (most recent call last):
  File "/usr/local/bin/multildapd.py", line 259, in <module>
    gevent.signal(signal.SIGTERM, stop_app, **{'pidfile': pidfile,
AttributeError: module 'gevent' has no attribute 'signal'
```

Did I something wrong? Which Python version should I use? Thanks.

Fanda

**Comment by peppelinux** [comment]
Hi @FandaOG 
thank you for this issues, I fixed this aspect in the last release of pymultildap
https://github.com/peppelinux/pyMultiLDAP/commit/afc7c9bb1421859f09ba08904b2b2c0adbdd1f24

**Comment by FandaOG** [comment]
Thank you. Now it works. But I can not make proxy work. I would like to use feature `LDAP client to many servers as a single one`.

The idea is, I will run multi-ldap server (`multildapd.py -conf settings.py -port 1234`). There will be few LDAP servers in settings.py. Then I will ask (standard ldap request) `ldapsearch -x -H ldap://127.0.0.1:1234 -b "dc=company,dc=com" "uid=foo.bar"`. multi-ldap ask every LDAP servers in settings until find first match.

My test

I runned multildap. Then I wanted to ask him to LDAP data (2nd window). Multildap detect new connection but did not ask ldap from config (ldap://10.255.254.40:1636). Can this util handle my use case (create ldap proxy for multiple ldap servers)? Thanks.
![image](https://user-images.githubusercontent.com/61017336/125614680-6aa7f4c1-fa3d-49e5-a645-9f9e806e06e4.png)

**Comment by peppelinux** [comment]
You have to configure slapd with sock backend as shown in the readme

**Comment by peppelinux** [comment]
otherwise pymultildap will be implemented in your project as a client LDAP library, but multi ldap :)

**Comment by peppelinux** [comment]
@FandaOG 
i fyou can't or won't use slapd as ldap server interface I'd suggest you to implement pymultildap in ldaptor 
https://github.com/twisted/ldaptor

I started a study here
https://github.com/peppelinux/pyMultiLDAP/tree/master/examples/ldaptor

And I think that it would be awesome to move forward in it, if you would like to join in

see also
https://ldaptor.readthedocs.io/en/latest/cookbook/merger.html

**Comment by FandaOG** [comment]
@peppelinux thank you very much. You are really helpful. I'll try it.

**Comment by peppelinux** [comment]
remember to put a star on this project ;)
